name: "Update Deployment Status and Add Outputs to Environment"

description: "Update deployment status and add outputs as environment variables when successful."

inputs:
  repository:
    description: "The repository in the format owner/repo."
    required: true
  token:
    description: "GitHub token with repo permissions."
    required: true
  outputs:
    description: "The outputs to store in the environment as JSON."
    required: true
  stage:
    description: "The name of the environment (stage) to update."
    required: true

runs:
  using: "composite"
  steps:
    - name: Set Environment Variables
      shell: bash
      env:
        REPO: ${{ inputs.repository }}
        TOKEN: ${{ inputs.token }}
        NEW_OUTPUTS: ${{ inputs.outputs }}
        STAGE: ${{ inputs.stage }}
      run: |
        set -e

        # Get SST_OUTPUTS variable (check if it exists)
        VAR=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/$REPO/environments/$STAGE/variables/SST_OUTPUTS")

        STRINGIFIED_OUTPUTS=$(echo "$NEW_OUTPUTS" | jq -c '.')

        # if value exists, update it, otherwise create it
        if [ "$(echo $VAR | jq .name)" == "null" ]; then
          echo "SST_OUTPUTS variable does not exist. Creating..."

          curl -s -X POST -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d "$(jq -n --arg name "SST_OUTPUTS" --arg value "$STRINGIFIED_OUTPUTS" '{name: $name, value: $value}')" \
            "https://api.github.com/repos/$REPO/environments/$STAGE/variables"

        else
          echo "SST_OUTPUTS variable exists. Updating..."

          curl -s -X PATCH -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d "$(jq -n --arg name "SST_OUTPUTS" --arg value "$STRINGIFIED_OUTPUTS" '{name: $name, value: $value}')" \
            "https://api.github.com/repos/$REPO/environments/$STAGE/variables/SST_OUTPUTS"
          exit 0
        fi
